### ISSUE TITLE
SQS trace header fails for unsampled traces

### ISSUE THREAD

**Issue by jimjshields** [aws/aws-xray-sdk-python#213]
We're using the XRay SDK for tracing our Django apps, which use SQS for asynchronous work. For the most part, it's sending traces of Django requests successfully and we can see them in the console.

However, we had an unsampled request that happened to interact with SQS, and it failed with this error:
```python
ClientError("An error occurred (InvalidParameterValue) when calling the GetQueueUrl operation: The request has a 'X-Amzn-Trace-Id' HTTP header which is reserved for AWS X-Ray trace header and has an invalid value 'Root=dummy;Parent={real_parent_id};Sampled=0'",)
```

It seems like unsampled requests get the `Root` of `dummy`, which seems to cause this validation exception in SQS. Ideally, it'd either have a real ID, or that header wouldn't be injected for unsampled requests.

We have:
* `python`: 3.6.5
* `aws-xray-sdk`: 2.4.2
* `boto3`: 1.9.230
* `botocore`: 1.12.253
* `django`: 2.0.4

Here's our configuration in `settings.py`:
```python
XRAY_RECORDER = {
    'AWS_XRAY_DAEMON_ADDRESS': f"{EC2_PRIVATE_IP}:{XRAY_PORT}",
    'AWS_XRAY_TRACING_NAME': xray_tracing_name,
    'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR',
    'PATCH_MODULES': [
        'boto3',
        'requests'
    ],
    'PLUGINS': ('EC2Plugin', 'ECSPlugin')
}
```
And the SDK is in our `INSTALLED_APPS` and `MIDDLEWARE`.

Let me know if you need more information. Thanks for the work on this library, I think it'll help us a lot!

**Comment by srprash** [comment]
Hi @jimjshields 
Thanks for bringing up this issue. If a trace is unsampled, the python SDK marks the traceid as `dummy` which fails a backend validation.
We have figured out the root cause of the issue and are working on rolling out a fix soon. I'd request you to please stay tuned for any updates.

Thanks.

**Comment by jimjshields** [comment]
That's great, thanks @srprash! Looking forward to a fix.

**Comment by myyee** [comment]
@srprash Do you have an ETA for the fix? It is affecting our production. Thanks.

**Comment by bhautikpip** [comment]
Hi @myyee,

SQS is aware of this issue and rolling out a fix soon.

**Comment by myyee** [comment]
Hi @bhautikpip ,
The X-Ray Python SDK crashed due to this underlying SQS issue. I ended up with nothing in the X-Ray because it fails to send the traces over. This is a totally hidden issue until someone informed me that things are not working correctly. Would you make an enhancement to the SDK so that it fails gracefully and still be able to send out traces to the X-Ray? Thanks.

**Comment by bhautikpip** [comment]
Hi @myyee,

Since this behavior is only visible in dummy segments. You might not have visibility of this issue on the console because XRay SDK never send out dummy segments to the daemon.

**Comment by bhautikpip** [comment]
Hello, 

Sorry for the inconvenience because of this issue. SQS has finished rollback so you might not be seeing this issue.

**Comment by xrn** [comment]
hi @jimjshields - you marked this issue as solved, this means that trace_id should be shared lambdas in composition lambda -> SQS -> lambda. Is it currently working for python SDK?

**Comment by srprash** [comment]
Hi @xrn 
This issue was regarding a bug that was introduced as part of our integration with SQS, where if an instrumented SQS client was making a call and the trace is unsampled, the application breaks with the error mentioned in the original post. This was fixed on our end.
I believe the problem you're describing relates to [this](https://github.com/aws/aws-xray-sdk-python/issues/173) issue.

**Comment by sachdevajanit123** [comment]
I can still see the issue , If all my requests are not sampled
An error occurred (InvalidParameterValue) when calling the DeleteMessage operation: The request has a 'X-Amzn-Trace-Id' HTTP header which is reserved for AWS X-Ray trace header and has an invalid value 'Root=dummy;Parent=39d23fb90647b57f;Sampled=1'

**Comment by srprash** [comment]
Hi @sachdevajanit123 ,
What's the version of the SDK you're using? This issue was fixed in the [v2.6.0](https://github.com/aws/aws-xray-sdk-python/blob/aed8e43fc03e68c0d012a6a6e11a2e859b0bf247/CHANGELOG.rst#260)
